#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# pynucastro documentation build configuration file, created by
# sphinx-quickstart on Wed Dec 27 11:54:03 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use pathlib.Path.resolve to make it absolute, like shown here.
#
import os
import sys
from importlib.metadata import version as importlib_version
from pathlib import Path

sys.path.insert(0, str(Path.cwd().parents[1]))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.autodoc',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.intersphinx',
    'sphinxcontrib.bibtex',
    'nbsphinx',
    'sphinx.ext.githubpages',
    'sphinx_copybutton',
    'sphinx-prompt',
    'sphinx_math_dollar',
    'sphinx_mdinclude',
    'myst_nb',
    'sphinx.ext.napoleon',
    'IPython.sphinxext.ipython_console_highlighting']

# bibtex
bibtex_bibfiles = ['refs.bib']
bibtex_reference_style = 'author_year'

linkcheck_ignore = [r"https://doi.org",
                    r"https://link.aps.org"]

linkcheck_retries = 3
linkcheck_timeout = 100
linkcheck_allow_unauthorized = True

autosummary_generate = True

# docstrings
autodoc_typehints = "none"

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# always execute notebooks
env_skip_execute = os.getenv("SKIP_EXECUTE")


if not env_skip_execute:
    nb_execution_mode = "force"
else:
    nb_execution_mode = "off"

nbsphinx_allow_errors = True
nbsphinx_timeout = 1000

# myst-nb control of notebooks
nb_execution_timeout = 500
nb_execution_allow_errors = True
myst_enable_extensions = ["dollarmath"]


# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The main toctree document.
main_doc = 'index'

# General information about the project.
project = 'pynucastro'
copyright = '2024-2025, pynucastro development team'
author = 'pynucastro development team'

#html_logo = "logo.png"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The full version, including alpha/beta/rc tags.
release = importlib_version("pynucastro")

# The short X.Y version.
version = '.'.join(release.split('.')[:2])

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["changelog.md"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# Enable linking references to other projects' documentation.
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'matplotlib': ('https://matplotlib.org/stable', None),
    "networkx": ('https://networkx.org/documentation/stable', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'sympy': ('https://docs.sympy.org/latest/', None),
    'yt': ('https://yt-project.org/doc', None),
    'unyt': ('https://unyt.readthedocs.io/en/stable', None),
}


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_book_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    "repository_url": "https://github.com/pynucastro/pynucastro",
    "use_repository_button": True,
    "use_issues_button": True,
    "use_edit_page_button": True,
    "use_source_button": True,
    "repository_branch": "main",
    "path_to_docs": "docs/source",
    "logo": {
        "text": f"pynucastro {version}",
        "image_light": "logo.png",
        "image_dark": "logo.png",
    }
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_css_files = ["myfile.css"]



# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'pynucastrodoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (main_doc, 'pynucastro.tex', 'pynucastro Documentation',
     'pynucastro development team', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (main_doc, 'pynucastro', 'pynucastro Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (main_doc, 'pynucastro', 'pynucastro Documentation',
     author, 'pynucastro', 'One line description of project.',
     'Miscellaneous'),
]
