NDEBUG := t
MPI    :=
OMP    := 

COMP := gfortran

MKVERBOSE := t

programs += main

<pynucastro_home>(0)

PROGRAM_DIR := $(shell pwd)

PROBIN_PARAMETER_DIRS := $(PROGRAM_DIR)

ALL:


include $(PYNUCASTRO_HOME)/util/F_mk/Gpynucastro.mak


ALL: $(pnames)

# include Makefile rules
include $(PYNUCASTRO_HOME)/util/F_mk/GMakerules.mak

