name: isort

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  isort:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: "pip"

      - name: Install dependencies + isort
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install isort

      - name: Install pynucastro
        run: pip install .

      - name: Validate
        run: isort --check --diff pynucastro
