name: pytest-all

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v6

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pynucastro
        run: pip install --editable .

      - name: Print system info
        run: |
          echo '::group::NumPy'
          pip install threadpoolctl &>/dev/null
          python -c "import sys, numpy; print(numpy.__version__); print(sys.version); print(numpy.show_runtime())"
          echo '::endgroup::'
          echo '::group::CPU info'
          lscpu
          echo '::endgroup::'
          echo '::group::Package versions'
          pip list --format=freeze
          echo '::endgroup::'

      - name: Get AMReX
        run: |
          mkdir external
          cd external
          git clone https://github.com/AMReX-Codes/amrex.git
          cd amrex
          git checkout development
          echo 'AMREX_HOME=$(GITHUB_WORKSPACE)/external/amrex' >> $GITHUB_ENV
          echo $AMREX_HOME
          if [[ -n "${AMREX_HOME}" ]]; then exit 1; fi
          cd ../..

      - name: Get Microphysics
        run: |
          cd external
          git clone https://github.com/AMReX-Astro/Microphysics.git
          cd Microphysics
          git checkout development
          echo 'MICROPHYSICS_HOME=$(GITHUB_WORKSPACE)/external/Microphysics' >> $GITHUB_ENV
          echo $MICROPHYSICS_HOME
          if [[ -n "${MICROPHYSICS_HOME}" ]]; then exit 1; fi
          cd ../..

      - name: Install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get -qq -y install curl cmake jq clang g++

      - name: Run tests with pytest
        run: pytest -v -s --nbval --cov=pynucastro --color=yes -n 4 --dist loadscope

      - name: Upload output from failed write_network tests
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: failed_networks_${{ matrix.python-version }}
          path: _test_*/
          if-no-files-found: ignore
          retention-days: 5
